const TYPES = {
    CREATE_TODO: "CREATE_TODO",
    DELETE_TODO: "DELETE_TODO",
    FINISH_TODO: "FINISH_TODO",
    EDIT_TODO: "EDIT_TODO",
    REOPEN_TODO: "REOPEN_TODO",
    ERASE_ALL_TODOS: "ERASE_ALL_TODOS",
    SET_TOTAL_PRODUCTIVITY_TIME: "SET_TOTAL_PRODUCTIVITY_TIME",
}

export default TYPES